// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace Combat::ActionTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Attack)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic_Attack_1)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic_Attack_2)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic_Attack_3)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic_Attack_4)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic_Attack_5)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Basic_Attack_6)

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Special_Attack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Special_Attack_EX)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ultimate)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Switch_In)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Switch_Out)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chain_Attack)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodge)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rush_Attack)
	
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quick_Assist)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Defensive_Assist)
}

namespace Team
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Agent)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy)
}

namespace Combat::Gait
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Run)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodge)
}

namespace Combat::Status::Agent
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Parry)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodge)
	
}

namespace Combat::Status::Enemy
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stunned)
}

namespace Combat::CombatWindows
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputBufferWindow)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ProceedWindow)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IsRecoveryWindow)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ParryWindow)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementInterruptWindow)
}

namespace Combat::Data
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DamageMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DazeMultiplier)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StunDMGMultiplier)
}

namespace Combat::Event
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChainAttack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(PerfectAssist)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuickAssist)
}

namespace Combat::SpecialAction
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChainAttack)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuickAssist)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(DefensiveAssist)
}

namespace Combat::Camera::Status
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatFollowCamera)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HighSpeedMovementCamera)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChainAttackCamera)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuickAssistCamera)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(UltimateCamera)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ParryCamera)
}


// BlackBoard
namespace AI::BlackBoard
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IsStunned)
}
